namespace EdmxToEfCore
{
	using Microsoft.Build.Framework;
	using Microsoft.Build.Utilities;
	using System.IO;
	using System.Linq;
	using System.Collections.Generic;
	using System.Xml.Serialization;

	public class EdmxToEfCoreTask : Task
	{
		public ITaskItem[] InputModels { get; set; }
		public bool AutoIncludeFromProject { get; set; } = true;
		public string OutputPathPattern { get; set; } = "%.autogenerated.cs";

		private string ToOutputPath(string input)
		{
			return Path.Combine(Path.GetDirectoryName(input),
				OutputPathPattern.Replace("%", Path.GetFileNameWithoutExtension(input)));
		}

		public override bool Execute()
		{
			var inputs = new List<string>();
			if (AutoIncludeFromProject)
			{
				inputs.AddRange(Directory.EnumerateFiles(".", "*.edmx", SearchOption.AllDirectories));
			}
			if (InputModels != null)
				inputs.AddRange(InputModels.Select(o => o.GetMetadata("FullPath")));

			foreach (var inFile in inputs.Distinct())
			{
				ModelToCode.ProcessFile(inFile, ToOutputPath(inFile), m => Log.LogMessage(m));
			}
			
			return false;
		}
	}
}